[windows]
student01 ansible_host=40.81.225.81

[windows:vars]
ansible_connection=psrp
ansible_port=5986
ansible_user=wakizu
ansible_password=!BRr39E,BAPUWq
ansible_psrp_auth=basic
ansible_psrp_cert_validation=ignore

[linux]
ubuntu01 ansible_connection=local

[linux:vars]
ansible_python_interpreter=/usr/bin/python3

[all:children]
windows
linux
