[linux]
localhost ansible_connection=local
web03 ansible_connection=docker ansible_python_interpreter=/usr/local/bin/python3.14

[containers]
web01 ansible_connection=docker ansible_python_interpreter=/usr/local/bin/python3.14
web02 ansible_connection=docker ansible_python_interpreter=/usr/local/bin/python3.14
